"""Initial migration.

Revision ID: 82b2371c3bdd
Revises: 
Create Date: 2023-03-17 10:19:18.869195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82b2371c3bdd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("hashUrl", sa.String(length=10), nullable=False),
        sa.Column("originalUrl", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("hashUrl"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url")
    # ### end Alembic commands ###
